name: Sync Fork

on:
  schedule:
    - cron: '*/30 * * * *' # Кожні 30 хвилин
  workflow_dispatch: # Ручний запуск

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Sync
        uses: repo-sync/github-sync@v2
        with:
          # Вказуємо ОРИГІНАЛЬНИЙ репозиторій (звідки беремо)
          source_repo: "https://github.com/coolzyd9107/GKI_ReSukiSU_SUSFS.git"
          # З якої гілки оригіналу брати
          source_branch: "main"
          # В яку гілку вашого форку класти
          destination_branch: "main"
          # Ваш токен
          github_token: ${{ secrets.GITHUB_TOKEN }}
